name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          - "5.16"
          - "5.24"
          - "5.30"
          - "5.38"
          - "5.40"
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: prepare
        run: |
          cpanm -nf Proc::Guard Number::Format
          gem install fluentd --no-document -v '~> 1.0'
      - name: test
        run: |
          cpanm --installdeps .
          perl Build.PL
          ./Build
          ./Build test
