name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          - "5.8"
          - "5.10"
          - "5.12"
          - "5.16"
          - "5.24"
          - "5.30"
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: prepare
        run: |
          cpanm -nf Proc::Guard Number::Format
          gem install fluentd --no-document -v '~> 1.0'
      - name: test
          cpanm --installdeps .
          perl Build.PL
          ./Build
          ./Build test
